### PR TITLE
DINT-554 stop endless errors when datastream id or ims org id are incorrect.

### PR DESCRIPTION
**Pull request by benjaminkalk**
## Description

Stop retrying to set consent, if request fails.

## Motivation and Context

(https://jira.corp.adobe.com/browse/DINT-554)

## How Has This Been Tested?

Use a bad datastream ID set via EPC admin panel.  
Go to the storefront web page.
Open the browser dev tools and observe 400 setConsent error occur only 1 time and does not reoccur until navigating to a new page.

## Types of changes

-   [ x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

-   [x ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
-   [ x] My code follows the code style of this project.
-   [ ] My change requires a change to the documentation.
-   [ ] I have updated the documentation accordingly.
-   [ ] I have read the **CONTRIBUTING** document.
-   [ ] I have added tests to cover my changes.
-   [ x] All new and existing tests passed.

### CODE REVIEW

**Review by aniham — CHANGES_REQUESTED** [review]
@benjaminkalk @grahamcrackers changing this to `setTimeout` defeats the purpose of why we have it - we want it to run at intervals in case a person sets consent cookie during their browsing experience. if we decide against this behavior (should check with product, etc), then we don't need `setTimeout` at all - but i don't believe that's the correct thing to do

**Comment by aniham** [comment]
@benjaminkalk totally agree - i def don't think we should keep failing, i just don't think `setTimeout` is the solution here :)

one thing i don't understand is - pardon my ignorance here - why are we in a situation where `getInstance` returns something valid even when ims org/datastream ids are messed up?

**Comment by benjaminkalk** [comment]
@aniham I don't think the configure actually makes any requests, so it doesn't know it is not configured.  Also, due to setting default consent to "pending" no requests will be made except for trying to update the consent, and so that is when it figures out the configuration is not correct.  This is somewhat documented here https://experienceleague.adobe.com/docs/experience-platform/edge/consent/supporting-consent.html?lang=en

**Comment by aniham** [comment]
@benjaminkalk so i know configure returns an error if the ims org/datastream are missing - but maybe it doesn't if they are wrong? is that true? if so, wouldn't all the send events be constantly throwing errors too?

**Comment by benjaminkalk** [comment]
@aniham I think you are correct that no value would error, but bad value does not because it is just "frontend" validation.  
When it is configured with the value of consent pending it will not send any events, and because the consent is never updated it continues to not send any events.

**Pull request merged**
